# Generated by Django 3.2.5 on 2021-10-06 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('google_maps_link', models.CharField(blank=True, max_length=2000, null=True)),
                ('location_street_address', models.CharField(blank=True, max_length=200, null=True)),
                ('location_town_state_zip', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
    ]
