# Generated by Django 3.2.5 on 2021-11-15 19:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_remove_orderlineitem_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guid',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
