# Generated by Django 3.2.5 on 2021-11-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sales_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
