# Generated by Django 3.2.5 on 2021-10-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('about_title', models.CharField(blank=True, max_length=500, null=True)),
                ('about_blurb', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
