# Generated by Django 3.2.5 on 2021-12-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textfield',
            name='about_blurb',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
